#!/bin/bash

echo "Conceptualization VCP (view-controller-partition) Architecture - by finnwinch📎"
echo "VCP architecture is developed to help young programmers in Garry's Mod without base knowledge or realm"
read -p "Please enter a unique and valid name for your script : " name
while test -d $name ; do
	read -p "Please enter a valide and unique name for your script : " name
done
path="/mnt/c/Program Files (x86)/Steam/steamapps/common/GarrysMod/server/garrysmod/addons"
main="if SERVER then include(\"$name/src/server/compile.lua\") end
if CLIENT then include(\"$name/src/client/compile.lua\") end"

clientCompile="include(\"$name/event/cl_init.lua\")
include(\"$name/cache/color.lua\")
MsgC(Color(255,0,0),\"@$name\",Color(0,255,0),\" LOAD \",Color(255,0,255),\"compile\")"

serverCompile="include(\"$name/src/server/ressource.lua\")
include(\"$name/event/sv_init.lua\")
include(\"$name/cache/color.lua\")
MsgC(Color(255,0,0),\"@$name\",Color(0,255,0),\" LOAD \",Color(255,0,255),\"compile\")"

clientGunit="MsgC(Color(255,0,0),\"@$name\",Color(0,255,0),\" LOAD \",Color(255,0,255),\"test unitaire\")
PrintTable(color_primary)"

serverGunit="MsgC(Color(255,0,0),\"@$name\",Color(0,255,0),\" LOAD \",Color(255,0,255),\"test unitaire\")
PrintTable(color_primary)"

clientMain="--[[
    you can code here your addons or, struct your file into code folder and include them here
    **NOTE to include all client file into src/server/ressource
    !! you have to include your code here!!!!!!!!!!!
]]"

serverMain="--[[
    you can code here your addons or, struct your file into code folder and include them here
    !! you have to include your code here!!!!!!!!!!!
]]"

ressource="AddCSLuaFile(\"$name/cache/color.lua\")
AddCSLuaFile(\"$name/src/client/compile.lua\")
AddCSLuaFile(\"$name/src/client/gunit.lua\")
AddCSLuaFile(\"$name/event/cl_init.lua\")
AddCSLuaFile(\"$name/src/client/main.lua\")
MsgC(Color(255,0,0),\"@$name\",Color(0,255,0),\" LOAD \",Color(255,0,255),\"ressource\")"

clientInit="hook.Add(\"PreGamemodeLoaded\",\"init the $name preparation\",function()
    include(\"$name/cache/color.lua\")
end)
hook.Add(\"PostGamemodeLoaded\",\"init the $name Gunit and addons\",function()
    include(\"$name/src/client/gunit.lua\")
    include(\"$name/src/client/main.lua\")
    MsgC(Color(255,0,0),\"@$name\",Color(0,255,0),\" have been charge since \",Color(0,200,255),\"i like cheese\")
end)"

serverInit="hook.Add(\"PreGamemodeLoaded\",\"init the $name preparation\",function()
    include(\"$name/cache/color.lua\")
end)
hook.Add(\"PostGamemodeLoaded\",\"init the $name Gunit and addons\",function()
    include(\"$name/src/server/gunit.lua\")
    include(\"$name/src/server/main.lua\")
    MsgC(Color(255,0,0),\"@$name\",Color(0,255,0),\" have been charge since \",Color(0,200,255),\"i like cheese\")
end)"

color="color_primary   = Color(0, 123, 255)
color_secondary = Color(108, 117, 125)
color_success   = Color(40, 167, 69)
color_danger    = Color(220, 53, 69)
color_warning   = Color(255, 193, 7)
color_info      = Color(23, 162, 184)
color_light     = Color(248, 249, 250)
color_dark      = Color(33, 37, 41)
color_greyDark  = Color(52, 58, 64)
color_mauve     = Color(128, 92, 145)
color_marine    = Color(60, 79, 118)"

cd "$path" && mkdir "$name" && cd "$name" || exit
git init
code .
mkdir lua && cd lua || exit
mkdir autorun && cd autorun || exit
echo -e "$main" > "$name.src.lua"

cd .. && mkdir "$name" && cd "$name" || exit
mkdir src && cd src || exit
mkdir client && cd client || exit
mkdir code
echo -e "$clientCompile" > compile.lua
echo -e "$clientGunit" > gunit.lua
echo -e "$clientMain" > main.lua

cd .. && mkdir server && cd server || exit
mkdir code
echo -e "$serverCompile" > compile.lua
echo -e "$serverGunit" > gunit.lua
echo -e "$serverMain" > main.lua
echo -e "$ressource" > ressource.lua

cd .. && cd ..
mkdir sql database package import connection class interface
cd interface || exit
mkdir layout design container components
cd ..

mkdir event && cd event || exit
echo -e "$clientInit" > cl_init.lua
echo -e "$serverInit" > sv_init.lua

cd .. && mkdir cache && cd cache || exit
echo -e "$color" > color.lua
echo "
$path
└── $name
    ├── lua
        ├── autorun
        │   └── $name.src.lua #autorunner. don't touch them
        └── $name
            ├── cache   #cache your variable here
            │   └── color.lua
            ├── database    #use your database module here
            ├── event   #implement your hook here
            │   ├── cl_init.lua #init the VCP
            │   └── sv_init.lua #init the VCP
            ├── import #import other code
            ├── interface #interface strucutre
            │   ├── components #interactivity
            │   ├── container #your other child
            │   ├── design #your paint part
            │   └── layout #yout windows with one parent
            ├── package #your own function
            ├── sql #data acces objet here (can be dao or table of function or what ever, but with db)
            └── src #you implement here your code
                ├── client #client realm
                │   ├── code #normally, you don't use them, but you can just put your folder here
                │   ├── compile.lua #compile part
                │   ├── gunit.lua #do your test here
                │   └── main.lua #do your code here and inclusion
                └── server #server realm
                    ├── code #normally, you don't use them, but you can just put your folder here
                    ├── compile.lua #compile part
                    ├── gunit.lua #do your test here
                    ├── main.lua #do your code here and inclusion
                    └── ressource.lua #download client part

"
read -p "Conceptualization VCP 3.8 Architecture Finished! Press enter to close." closed
