#!/bin/bash
echo "Conceptualization VCP (view-controler-partition) Architecture - by finnwinch📎"
echo "VC Architecture was used to sperate action by level of design"
read -p "Please enter the name of your script : " name
cd "/mnt/c/Program Files (x86)/Steam/steamapps/common/GarrysMod/server/garrysmod/addons"
while test -d $name ; do
	read -p "Please enter a valide and unique name for your script : " name
done
mkdir $name
cd $name
git init
mkdir lua
cd lua
mkdir autorun
cd autorun
touch $name.src.lua #loader	include src parts
code="
if SERVER then include("\$name/src/server/compile.lua\") end
if CLIENT then include("\$name/src/client/compile.lua\") end
"
echo "$code" >> $name.src.lua
cd ..
mkdir $name
cd $name
mkdir cache #cache color/materials/any
read -p "do you want to precache default color ? (empty for no) : " color_preselected
if test ! -v $color_preselected ; then
	cd cache
	touch color.lua
	color_lists="color_primary   = Color(0, 123, 255)
color_secondary = Color(108, 117, 125)
color_success   = Color(40, 167, 69)
color_danger    = Color(220, 53, 69)
color_warning   = Color(255, 193, 7)
color_info      = Color(23, 162, 184)
color_light     = Color(248, 249, 250)
color_dark      = Color(33, 37, 41)
color_greyDark  = Color(52, 58, 64)
color_mauve     = Color(128, 92, 145)
color_marine    = Color(60, 79, 118)"
	echo "$color_lists" > color.lua
	cd ..
fi
cd ..
code $name
cd $name
mkdir class #class for management your addons
cd class
mkdir core
#cd core
#touch server.lua	#addons controller SERVER
#touch client.lua  #addons controller CLIENT
#cd ..
cd ..
mkdir connection #folder contain networking
mkdir database #code about your table / droptable
mkdir event #your hook used
cd event
code = "
hook.Add("PreGamemodeLoaded","\init the $name\",function()
    include("\$name/cache/color.lua\")
end)
hook.Add("PostGamemodeLoaded","\init the $nameGunit\",function()
    include("\$name/src/client/gunit.lua\")
    include("\$name/src/client/main.lua\")
    MsgC(Color(255,0,0),"\@$name\",Color(0,255,0)," have been charge since ",Color(0,200,255),"i like cheese \n")
end)
"
echo $code > cl_init.lua
code = "
hook.Add("PreGamemodeLoaded","\init the $name\",function()
    include("\$name/cache/color.lua\")
end)
hook.Add("PostGamemodeLoaded","\init the $nameGunit\",function()
    include("\$name/src/server/gunit.lua\")
    include("\$name/src/server/main.lua\")
    MsgC(Color(255,0,0),"\@$name\",Color(0,255,0)," have been charge since ",Color(0,200,255),"i like cheese \n")
end)
"
echo $code > sv_init.lua
cd ..
mkdir import #all file imported, like framework
mkdir interface #folder contain interface parts
cd interface
mkdir components #interaction about your layout
mkdir container #elements into your layout
mkdir layout #frame container with only first childen
mkdir design #paint section !deprecreate, mayby, idk
cd ..
mkdir package #develop your own function to use
mkdir sql #data access object
#mkdir config #folder contain config
#cd config
#touch $name.cfg.lua
#cd ..
mkdir src #used for test implementation and final put data like pre config setup
cd src
mkdir server
ressource = "
"
gunit = "
"
main = "
"
mkdir client
read -p "Conceptualization VCP 3.2 Architecture Finished!" closed
